version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgresapp
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask-app:
    container_name: flask-container
    image: flask:0.0.6
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgresapp:root@postgres/app
    depends_on:
      - postgres

volumes:
  postgres-data:
